version: '3'
services:
    shoppinglist_db: 
        container_name: shoppinglist-postgresql-db
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DATABASE}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - shoppinglist_network
    shoppinglist_api:
        container_name: shoppinglist-api
        build: .
        env_file: 
            - .env
        ports:
            - ${API_PORT}:${API_PORT}
        depends_on:
            - shoppinglist_db
        networks:
            - shoppinglist_network
networks:
    shoppinglist_network:
        driver: bridge